FROM n3robot-base:latest

ARG TELEGRAM_BOT_TOKEN_ARG
ARG PROJECT_URL_ARG
ARG MONGODB_PASSWORD_ARG

ENV FLASK_APP=api.py
ENV TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN_ARG
ENV PROJECT_URL=$PROJECT_URL_ARG
ENV MONGODB_PASSWORD=$MONGODB_PASSWORD_ARG

WORKDIR n3robot

COPY . .
